POST http://localhost:3000/user
Content-Type: application/json

{ "operation": "read-update", "id": "7d532d4c-17ac-4ef1-8efe-aaff83a50df4", "pageNumber": 9, "placeholder": "melhor-do-que-nos-filmes" }

###

POST http://localhost:3000/user
Content-Type: application/json

{ "operation": "pnts-get", "id": "7d532d4c-17ac-4ef1-8efe-aaff83a50df4", "pnts": -5 }